package io.github.navpil.testlogging.ourlib;

import org.junit.Test;

public class MainTest {

    @Test
    public void test() throws InterruptedException {
        Main.callWithError();
    }

}